import unittest
import os
from main import TextProcessor, MariaDBManagement


class TestProcessor(unittest.TestCase):

    def setUp(self):
        import os
        self.BASE_PATH = os.path.dirname(os.path.abspath(__file__))
        self.filepath = ""
        # A variable to maintain at the end of each test
        # files generated by them
        self.maintain_files = False

    def test_csv_read(self):
        filepath = self.BASE_PATH + "/mockups/complaints.csv"
        processor = TextProcessor()
        processor.read_csv(filepath)

    def test_finto_creazione_tabelle(self):
        conection = MariaDBManagement()

    def tearDown(self):
        if os.path.exists(self.filepath) and not self.maintain_files:
            os.unlink(self.filepath)

